/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.app.view;


import br.app.view.dadosPessoais.dao.DadosPessoaisDAO;
import br.app.view.table.QueryTableModel;
import br.cadastro.app.aluno.dao.AlunoDAO;
import br.cadastro.app.aluno.model.Aluno;
import br.cadastro.app.aluno.utils.ValidatorAluno;
import br.cadastro.app.contatos.utils.ValidatorContatos;
import br.cadastro.app.endereco.utils.ValidatorEndereco;
import br.cadastro.app.model.Contatos;
import br.cadastro.app.model.Endereco;
import br.cadastro.app.utils.Validator;
import java.awt.Color;
import java.awt.Frame;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author mvictor
 */
public final class TelaAluno extends javax.swing.JFrame {
    
    
    private final String sql = "SELECT a.id, a.nome, a.cpf, c.celular, c.email  FROM aluno a JOIN contatos c ON c.aluno_id = a.id";
    private final String colunas[] ={"ID", "Nome", "CPF", "Celular", "E-mail"};
    private QueryTableModel model;
    private int posicao;
    private String cpf;
    private int aluno_id;
    private final ValidatorAluno valA;
    private final ValidatorContatos valC;
    private final ValidatorEndereco valE;
    private final Validator val;
    /**
     * Creates new form TelaAluno
     */
    
    private void setLarguraFixo(){
        tblAluno.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblAluno.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblAluno.getColumnModel().getColumn(2).setPreferredWidth(200);
        tblAluno.getColumnModel().getColumn(3).setPreferredWidth(200);
        tblAluno.getColumnModel().getColumn(4).setPreferredWidth(400);
    }
    
    public TelaAluno() {
        val = Validator.getInstance();
        valA = ValidatorAluno.getInstance();
        valC = ValidatorContatos.getInstance();
        valE = ValidatorEndereco.getInstance();
        this.posicao = 0;
        this.cpf = null;
        this.model = new QueryTableModel(sql, colunas);
        initComponents(); 
        tblAluno.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblAluno.setAutoCreateRowSorter(true);
        tblAluno.setModel(model);
        setLarguraFixo();
        tblAluno.setBackground(Color.WHITE);
        tblAluno.setCellSelectionEnabled(true);
        tblAluno.getTableHeader().setReorderingAllowed(false);
        tblAluno.setSelectionMode(0); 
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtabpainel = new javax.swing.JTabbedPane();
        painelFormulario = new javax.swing.JPanel();
        lblnome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtcpf = new javax.swing.JFormattedTextField();
        lblcpf = new javax.swing.JLabel();
        lblcel = new javax.swing.JLabel();
        txtcelular = new javax.swing.JFormattedTextField();
        lbltelefone = new javax.swing.JLabel();
        txttelefone = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lbllogradouro = new javax.swing.JLabel();
        txtrua = new javax.swing.JTextField();
        lblbairro = new javax.swing.JLabel();
        txtbairro = new javax.swing.JTextField();
        lblcidade = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        lblcomplemento = new javax.swing.JLabel();
        txtcomplemento = new javax.swing.JTextField();
        lblcomplemento1 = new javax.swing.JLabel();
        jboxUF = new javax.swing.JComboBox<>();
        lblcep = new javax.swing.JLabel();
        txtcep = new javax.swing.JFormattedTextField();
        lblnumero = new javax.swing.JLabel();
        txtnumero = new javax.swing.JFormattedTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        bntSave = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lblCpfBusca = new javax.swing.JLabel();
        txtcpfbusca = new javax.swing.JFormattedTextField();
        btnBusca = new javax.swing.JButton();
        bntSave1 = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAluno = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelVoltar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtabpainel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtabpainel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtabpainelStateChanged(evt);
            }
        });
        jtabpainel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtabpainelFocusGained(evt);
            }
        });
        jtabpainel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabpainelMouseClicked(evt);
            }
        });
        jtabpainel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtabpainelKeyPressed(evt);
            }
        });

        lblnome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnome.setText("Nome Completo");

        txtnome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtcpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblcpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcpf.setText("CPF");

        lblcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcel.setText("CEL");

        try {
            txtcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lbltelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltelefone.setText("Tel");

        try {
            txttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblemail.setText("E-mail");

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lbllogradouro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbllogradouro.setText("Rua/Avenida/Logradouro");

        txtrua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblbairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblbairro.setText("Bairro");

        txtbairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblcidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcidade.setText("Cidade");

        txtcidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblcomplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcomplemento.setText("Complemento");

        txtcomplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblcomplemento1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcomplemento1.setText("UF");

        jboxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        lblcep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcep.setText("CEP");

        try {
            txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblnumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnumero.setText("Numero");

        txtnumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtnumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/removerCliente_icone.png"))); // NOI18N
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setDefaultCapable(false);
        btnDelete.setFocusPainted(false);
        btnDelete.setRequestFocusEnabled(false);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editCliente_icone.png"))); // NOI18N
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setDefaultCapable(false);
        btnUpdate.setFocusPainted(false);
        btnUpdate.setRequestFocusEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        bntSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/addCliente_icone.png"))); // NOI18N
        bntSave.setBorderPainted(false);
        bntSave.setContentAreaFilled(false);
        bntSave.setDefaultCapable(false);
        bntSave.setFocusPainted(false);
        bntSave.setRequestFocusEnabled(false);
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });

        lblCpfBusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCpfBusca.setText("CPF");

        try {
            txtcpfbusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpfbusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        bntSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/clear.png"))); // NOI18N
        bntSave1.setBorderPainted(false);
        bntSave1.setContentAreaFilled(false);
        bntSave1.setDefaultCapable(false);
        bntSave1.setFocusPainted(false);
        bntSave1.setRequestFocusEnabled(false);
        bntSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSave1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFormularioLayout = new javax.swing.GroupLayout(painelFormulario);
        painelFormulario.setLayout(painelFormularioLayout);
        painelFormularioLayout.setHorizontalGroup(
            painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFormularioLayout.createSequentialGroup()
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFormularioLayout.createSequentialGroup()
                        .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelFormularioLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblemail)
                                    .addComponent(lblnome)
                                    .addComponent(lblcpf)
                                    .addComponent(lbllogradouro)
                                    .addComponent(lblbairro)
                                    .addComponent(lblcomplemento)
                                    .addComponent(lblcep))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(painelFormularioLayout.createSequentialGroup()
                                            .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblcel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbltelefone)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtrua, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelFormularioLayout.createSequentialGroup()
                                        .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(painelFormularioLayout.createSequentialGroup()
                                                .addComponent(txtcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblcomplemento1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelFormularioLayout.createSequentialGroup()
                                                .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblcidade))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelFormularioLayout.createSequentialGroup()
                                                .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblnumero)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtcidade, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                                .addComponent(jboxUF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(painelFormularioLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(bntSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bntSave)
                                .addGap(36, 36, 36)
                                .addComponent(btnUpdate)
                                .addGap(39, 39, 39)
                                .addComponent(btnDelete)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(painelFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2))))
                .addContainerGap())
            .addGroup(painelFormularioLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(lblCpfBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcpfbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelFormularioLayout.setVerticalGroup(
            painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFormularioLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCpfBusca)
                        .addComponent(txtcpfbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnome)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcpf)
                    .addComponent(lblcel)
                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltelefone)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllogradouro)
                    .addComponent(txtrua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbairro)
                    .addComponent(lblcidade)
                    .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcomplemento)
                    .addComponent(lblcomplemento1)
                    .addComponent(jboxUF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcep)
                    .addComponent(lblnumero)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(bntSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntSave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtabpainel.addTab("Formulario", painelFormulario);

        panelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTableMouseClicked(evt);
            }
        });

        tblAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAluno);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editCliente_icone.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atualizar.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        jtabpainel.addTab("Informações", panelTable);

        panelVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVoltarMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Voltar ao Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVoltarLayout = new javax.swing.GroupLayout(panelVoltar);
        panelVoltar.setLayout(panelVoltarLayout);
        panelVoltarLayout.setHorizontalGroup(
            panelVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVoltarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(509, Short.MAX_VALUE))
        );
        panelVoltarLayout.setVerticalGroup(
            panelVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVoltarLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addContainerGap(521, Short.MAX_VALUE))
        );

        jtabpainel.addTab("Voltar ao Menu", panelVoltar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabpainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabpainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVoltarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelVoltarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaMenu telaMenu = new TelaMenu();
        telaMenu.setExtendedState(Frame.MAXIMIZED_BOTH);
        telaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
        // TODO add your handling code here:
        DadosPessoaisDAO dao = new DadosPessoaisDAO();
        /*Contatos*/
        
        boolean status; 
        
        try{
             if(val.isNotEmpty(txtnome.getText()) && val.isNotEmpty(txtcpf.getText()) &&
                val.isNotEmpty(txttelefone.getText()) && val.isNotEmpty(txtcelular.getText()) &&
                val.isNotEmpty(txtemail.getText()) && val.isNotEmpty(txtrua.getText()) &&
                val.isNotEmpty(txtbairro.getText()) && val.isNotEmpty(txtcomplemento.getText()) &&
                val.isNotEmpty(txtnumero.getText()) && val.isNotEmpty(txtcep.getText()) &&
                val.isNotEmpty(txtcidade.getText())){
                 
                Contatos contatos = new Contatos();
                contatos.setId(0);
                contatos.setTelefone(txttelefone.getText());
                contatos.setCelular(txtcelular.getText());
                contatos.setEmail(txtemail.getText());
                contatos.setAluno_id(0);

                /* Endereco */
                Endereco endereco = new Endereco();
                endereco.setId(0);
                endereco.setLogradouro(txtrua.getText());
                endereco.setBairro(txtbairro.getText());
                endereco.setComplemento(txtcomplemento.getText());
                endereco.setNumero(Integer.parseInt(txtnumero.getText()));
                endereco.setCep(txtcep.getText());
                endereco.setCidade(txtcidade.getText());
                endereco.setUf(jboxUF.getSelectedItem().toString());
                endereco.setAluno_id(0);

                /* Aluno */
                Aluno aluno = new Aluno();
                aluno.setId(0);
                aluno.setNome(txtnome.getText());
                aluno.setCpf(txtcpf.getText());
                aluno.setEndereco(endereco);
                aluno.setContatos(contatos);
                status = dao.saveDadosPessoais(aluno, contatos, endereco);
                
                if(status){
                    clear();
                    JOptionPane.showMessageDialog(this, "Informações foram salvas com sucesso...");
                    validar();
                }
                
            }
            else{
                validar();
                JOptionPane.showMessageDialog(this, "Preencha os campos em vermelho.");
            }
             
        }catch(HeadlessException | NumberFormatException e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_bntSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //pega o indice da linha
        int linha = tblAluno.getSelectedRow();
        //pega o indice da coluna
        int coluna = tblAluno.getSelectedColumn();
        
        
        if(tblAluno.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Você precisa selecionar um item da tabela");
        }
        else{
            try{
                this.posicao  = Integer.parseInt(tblAluno.getValueAt(linha,0).toString());
                this.cpf = tblAluno.getValueAt(linha, 2).toString();
                
                jtabpainel.setSelectedIndex(0);

                AlunoDAO alunoDAO = new AlunoDAO();

                String cpfBusca = this.cpf;
                Aluno alunos =  alunoDAO.findByCpf(cpfBusca);
                this.aluno_id = alunos.getId();
                txtcpfbusca.setText(cpf);
                txtnome.setText(alunos.getNome());
                txtcpf.setText(alunos.getCpf());
                //contatos
                txtcelular.setText(alunos.getContatos().getCelular());
                txttelefone.setText(alunos.getContatos().getTelefone());
                txtemail.setText(alunos.getContatos().getEmail());
                int aluno_id_contatos = alunos.getContatos().getAluno_id();
                //endereco
                txtrua.setText(alunos.getEndereco().getLogradouro());
                txtbairro.setText(alunos.getEndereco().getBairro());
                txtcidade.setText(alunos.getEndereco().getCidade());
                txtcomplemento.setText(alunos.getEndereco().getComplemento());
                String opcaoSelecionada = alunos.getEndereco().getUf();
                this.jboxUF.setSelectedItem(opcaoSelecionada);
                txtcep.setText(alunos.getEndereco().getCep());
                txtnumero.setText(String.valueOf(alunos.getEndereco().getNumero()));
                int aluno_id_endereco = alunos.getEndereco().getAluno_id();
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Erro na base de dados.");
            }
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtabpainelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabpainelMouseClicked
        // TODO add your handling code here:
        model.updateTable();
    }//GEN-LAST:event_jtabpainelMouseClicked

    private void tblAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblAlunoMouseClicked

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
        AlunoDAO alunoDAO = new AlunoDAO();
        try{
            String cpfBusca = this.txtcpfbusca.getText();
            Aluno alunos =  alunoDAO.findByCpf(cpfBusca);
            this.aluno_id = alunos.getId();
            txtnome.setText(alunos.getNome());
            txtcpf.setText(alunos.getCpf());
            //contatos
            txtcelular.setText(alunos.getContatos().getCelular());
            txttelefone.setText(alunos.getContatos().getTelefone());
            txtemail.setText(alunos.getContatos().getEmail());
            int aluno_id_contatos = alunos.getContatos().getAluno_id();
            //endereco
            txtrua.setText(alunos.getEndereco().getLogradouro());
            txtbairro.setText(alunos.getEndereco().getBairro());
            txtcidade.setText(alunos.getEndereco().getCidade());
            txtcomplemento.setText(alunos.getEndereco().getComplemento());
            String opcaoSelecionada = alunos.getEndereco().getUf();
            this.jboxUF.setSelectedItem(opcaoSelecionada);
            txtcep.setText(alunos.getEndereco().getCep());
            txtnumero.setText(String.valueOf(alunos.getEndereco().getNumero()));
            int aluno_id_endereco = alunos.getEndereco().getAluno_id();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Campo CPF vázio ou CPF não registrado!");
        }
        
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void panelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTableMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_panelTableMouseClicked

    private void jtabpainelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtabpainelFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtabpainelFocusGained

    private void jtabpainelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtabpainelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtabpainelKeyPressed

    private void jtabpainelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtabpainelStateChanged
        // TODO add your handling code here:
        int selecionado = jtabpainel.getSelectedIndex();
        if(selecionado == 1){
            this.model.fireTableDataChanged();
        }
    }//GEN-LAST:event_jtabpainelStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        updateTable();
        setLarguraFixo();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bntSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSave1ActionPerformed
        // TODO add your handling code here:
        clear();
        JOptionPane.showMessageDialog(rootPane, "Campos já forma limpos.");
    }//GEN-LAST:event_bntSave1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DadosPessoaisDAO dao = new DadosPessoaisDAO();
        /*Contatos*/
        
        boolean status; 
        
        try{
             if(val.isNotEmpty(txtnome.getText()) && val.isNotEmpty(txtcpf.getText()) &&
                val.isNotEmpty(txttelefone.getText()) && val.isNotEmpty(txtcelular.getText()) &&
                val.isNotEmpty(txtemail.getText()) && val.isNotEmpty(txtrua.getText()) &&
                val.isNotEmpty(txtbairro.getText()) && val.isNotEmpty(txtcomplemento.getText()) &&
                val.isNotEmpty(txtnumero.getText()) && val.isNotEmpty(txtcep.getText()) &&
                val.isNotEmpty(txtcidade.getText())){
                 
                Contatos contatos = new Contatos();
                contatos.setId(this.aluno_id);
                contatos.setTelefone(txttelefone.getText());
                contatos.setCelular(txtcelular.getText());
                contatos.setEmail(txtemail.getText());
                contatos.setAluno_id(0);

                /* Endereco */
                Endereco endereco = new Endereco();
                endereco.setId(this.aluno_id);
                endereco.setLogradouro(txtrua.getText());
                endereco.setBairro(txtbairro.getText());
                endereco.setComplemento(txtcomplemento.getText());
                endereco.setNumero(Integer.parseInt(txtnumero.getText()));
                endereco.setCep(txtcep.getText());
                endereco.setCidade(txtcidade.getText());
                endereco.setUf(jboxUF.getSelectedItem().toString());
                endereco.setAluno_id(0);

                /* Aluno */
                Aluno aluno = new Aluno();
                aluno.setId(this.aluno_id);
                aluno.setNome(txtnome.getText());
                aluno.setCpf(txtcpf.getText());
                aluno.setEndereco(endereco);
                aluno.setContatos(contatos);
                status = dao.updateDadosPessoais(aluno, contatos, endereco);
                
                if(status){
                    clear();
                    JOptionPane.showMessageDialog(this, "Informações foram atualizadas...");
                    validar();
                }
                
            }
            else{
                validar();
                JOptionPane.showMessageDialog(this, "Preencha os campos em vermelho.");
            }
             
        }catch(HeadlessException | NumberFormatException e){
            System.out.println("Error");
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSave;
    private javax.swing.JButton bntSave1;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jboxUF;
    private javax.swing.JTabbedPane jtabpainel;
    private javax.swing.JLabel lblCpfBusca;
    private javax.swing.JLabel lblbairro;
    private javax.swing.JLabel lblcel;
    private javax.swing.JLabel lblcep;
    private javax.swing.JLabel lblcidade;
    private javax.swing.JLabel lblcomplemento;
    private javax.swing.JLabel lblcomplemento1;
    private javax.swing.JLabel lblcpf;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lbllogradouro;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lbltelefone;
    private javax.swing.JPanel painelFormulario;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelVoltar;
    private javax.swing.JTable tblAluno;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JFormattedTextField txtcelular;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JFormattedTextField txtcpfbusca;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnome;
    private javax.swing.JFormattedTextField txtnumero;
    private javax.swing.JTextField txtrua;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables

    private void updateTable() {
       // TODO add your handling code here:
        model = new QueryTableModel(sql, colunas);
        this.tblAluno.setModel(model);
        this.model.fireTableDataChanged();
    }
    
    private void clear(){
        txtnome.setText(null);
        txtcpf.setText(null);
        txtcelular.setText(null);
        txttelefone.setText(null);
        txtemail.setText(null);
        txtrua.setText(null);
        txtbairro.setText(null);
        txtcidade.setText(null);
        txtcomplemento.setText(null);
        txtcep.setText(null);
        txtnumero.setText(null);
    }
    
    private void validar() {
        try{
            val.isFieldEmpty(this.txtnome);
            val.isEmptyCPF(this.txtcpf);
            val.isEmptyCelular(this.txtcelular);
            val.isEmptyTelefone(this.txttelefone);
            val.isEmptyCep(this.txtcep);
            val.isFieldEmpty(this.txtrua);
            val.isFieldEmpty(this.txtbairro);
            val.isFieldEmpty(this.txtcidade);
            val.isFieldEmpty(this.txtcomplemento);
            val.isFieldEmpty(this.txtemail);  
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
}
